### PR TITLE
Add js workflow sample

### PR DESCRIPTION
**Pull request by Eileen-Yu**
Keep same apis and logic with the other samples:

```
❯ dg dev start
Using default dev file dev-wf-js.yaml
⌛ Starting app "order-workflow"...
✅ Started app "order-workflow" successfully
== APP - order-workflow ==
== APP - order-workflow == > javascript@1.0.0 start
== APP - order-workflow == > node index.js
== APP - order-workflow ==
== APP - order-workflow == Starting workflow runtime...
== APP - order-workflow == http and https schemes are deprecated, use grpc or grpcs instead
== APP - order-workflow == http and https schemes are deprecated, use grpc or grpcs instead
== APP - order-workflow == Server is running on port 5001
== APP - order-workflow == Successfully connected to dns:grpc-prj468326.api.dev.cloud.diagrid.io:443. Waiting for work items...
== APP - order-workflow == Workflow runtime started successfully
== APP - order-workflow == Starting new orderProcessingWorkflow instance with ID = bcf27192-e5bc-487d-ab67-0c4f936bb2fd
== APP - order-workflow == Received "Orchestrator Request" work item with instance id 'bcf27192-e5bc-487d-ab67-0c4f936bb2fd'
== APP - order-workflow == bcf27192-e5bc-487d-ab67-0c4f936bb2fd: Rebuilding local state with 0 history event...
== APP - order-workflow == bcf27192-e5bc-487d-ab67-0c4f936bb2fd: Processing 2 new history event(s): [ORCHESTRATORSTARTED=1, EXECUTIONSTARTED=1]
== APP - order-workflow == Order received: {"Name":"Car","Quantity":2}
== APP - order-workflow == bcf27192-e5bc-487d-ab67-0c4f936bb2fd: Waiting for 1 task(s) and 0 event(s) to complete...
== APP - order-workflow == bcf27192-e5bc-487d-ab67-0c4f936bb2fd: Returning 1 action(s)
== APP - order-workflow == Workflow scheduled with ID: bcf27192-e5bc-487d-ab67-0c4f936bb2fd
== APP - order-workflow == Waiting 30 seconds for instance bcf27192-e5bc-487d-ab67-0c4f936bb2fd to complete...
== APP - order-workflow == Received "Activity Request" work item
== APP - order-workflow == Notification: Received order for 2 Car!
== APP - order-workflow == Activity notifyActivity completed with output undefined (0 chars)
== APP - order-workflow == Received "Orchestrator Request" work item with instance id 'bcf27192-e5bc-487d-ab67-0c4f936bb2fd'
== APP - order-workflow == bcf27192-e5bc-487d-ab67-0c4f936bb2fd: Rebuilding local state with 3 history event...
== APP - order-workflow == Order received: {"Name":"Car","Quantity":2}
== APP - order-workflow == bcf27192-e5bc-487d-ab67-0c4f936bb2fd: Processing 2 new history event(s): [ORCHESTRATORSTARTED=1, TASKCOMPLETED=1]
== APP - order-workflow == bcf27192-e5bc-487d-ab67-0c4f936bb2fd: Waiting for 1 task(s) and 0 event(s) to complete...
== APP - order-workflow == bcf27192-e5bc-487d-ab67-0c4f936bb2fd: Returning 1 action(s)
== APP - order-workflow == Received "Activity Request" work item
== APP - order-workflow == Verifying inventory for 2 Car
== APP - order-workflow == 2 Car(s) reserved. 48 left.
== APP - order-workflow == Activity reserveInventoryActivity completed with output {"success":true,"inventory_item":{"Name":"Car","Quantity":50}} (62 chars)
== APP - order-workflow == Received "Orchestrator Request" work item with instance id 'bcf27192-e5bc-487d-ab67-0c4f936bb2fd'
== APP - order-workflow == bcf27192-e5bc-487d-ab67-0c4f936bb2fd: Rebuilding local state with 6 history event...
== APP - order-workflow == Order received: {"Name":"Car","Quantity":2}
== APP - order-workflow == bcf27192-e5bc-487d-ab67-0c4f936bb2fd: Processing 2 new history event(s): [ORCHESTRATORSTARTED=1, TASKCOMPLETED=1]
== APP - order-workflow == bcf27192-e5bc-487d-ab67-0c4f936bb2fd: Waiting for 1 task(s) and 0 event(s) to complete...
== APP - order-workflow == bcf27192-e5bc-487d-ab67-0c4f936bb2fd: Returning 1 action(s)
== APP - order-workflow == Received "Activity Request" work item
== APP - order-workflow == Processing payment for 2 Car
== APP - order-workflow == Payment processed successfully
== APP - order-workflow == Activity processPaymentActivity completed with output undefined (0 chars)
== APP - order-workflow == Received "Orchestrator Request" work item with instance id 'bcf27192-e5bc-487d-ab67-0c4f936bb2fd'
== APP - order-workflow == bcf27192-e5bc-487d-ab67-0c4f936bb2fd: Rebuilding local state with 9 history event...
== APP - order-workflow == Order received: {"Name":"Car","Quantity":2}
== APP - order-workflow == bcf27192-e5bc-487d-ab67-0c4f936bb2fd: Processing 2 new history event(s): [ORCHESTRATORSTARTED=1, TASKCOMPLETED=1]
== APP - order-workflow == bcf27192-e5bc-487d-ab67-0c4f936bb2fd: Waiting for 1 task(s) and 0 event(s) to complete...
== APP - order-workflow == bcf27192-e5bc-487d-ab67-0c4f936bb2fd: Returning 1 action(s)
== APP - order-workflow == Received "Activity Request" work item
== APP - order-workflow == Updating inventory for 2 Car
== APP - order-workflow == Updated Car inventory to 48 remaining.
== APP - order-workflow == Activity updateInventoryActivity completed with output {"success":true,"inventory_item":{"Name":"Car","Quantity":48}} (62 chars)
== APP - order-workflow == Received "Orchestrator Request" work item with instance id 'bcf27192-e5bc-487d-ab67-0c4f936bb2fd'
== APP - order-workflow == bcf27192-e5bc-487d-ab67-0c4f936bb2fd: Rebuilding local state with 12 history event...
== APP - order-workflow == Order received: {"Name":"Car","Quantity":2}
== APP - order-workflow == bcf27192-e5bc-487d-ab67-0c4f936bb2fd: Processing 2 new history event(s): [ORCHESTRATORSTARTED=1, TASKCOMPLETED=1]
== APP - order-workflow == bcf27192-e5bc-487d-ab67-0c4f936bb2fd: Waiting for 1 task(s) and 0 event(s) to complete...
== APP - order-workflow == bcf27192-e5bc-487d-ab67-0c4f936bb2fd: Returning 1 action(s)
== APP - order-workflow == Received "Activity Request" work item
== APP - order-workflow == Notification: Order has completed!
== APP - order-workflow == Activity notifyActivity completed with output undefined (0 chars)
== APP - order-workflow == Received "Orchestrator Request" work item with instance id 'bcf27192-e5bc-487d-ab67-0c4f936bb2fd'
== APP - order-workflow == bcf27192-e5bc-487d-ab67-0c4f936bb2fd: Rebuilding local state with 15 history event...
== APP - order-workflow == Order received: {"Name":"Car","Quantity":2}
== APP - order-workflow == bcf27192-e5bc-487d-ab67-0c4f936bb2fd: Processing 2 new history event(s): [ORCHESTRATORSTARTED=1, TASKCOMPLETED=1]
== APP - order-workflow == bcf27192-e5bc-487d-ab67-0c4f936bb2fd: Orchestration completed with status COMPLETED
== APP - order-workflow == bcf27192-e5bc-487d-ab67-0c4f936bb2fd: Returning 1 action(s)
== APP - order-workflow == Instance bcf27192-e5bc-487d-ab67-0c4f936bb2fd completed
== APP - order-workflow == Workflow completed!
```

### CODE REVIEW

**Comment by famarting** [comment]
could you rebase from main?

**Comment by Eileen-Yu** [comment]
> could you rebase from main?

rebased

**Comment by famarting** [comment]
just pushed a commit, all quickstarts need to have the same behavior!

**Review by famarting — APPROVED** [review]

**Comment by famarting** [comment]
you'll need to update the CLI to allow the workflows js quickstart, dont forget to update the quickstarts e2e tests @Eileen-Yu

**Pull request merged**
