### PR TITLE
Fixes for Java and Python

### PR DESCRIPTION
**Pull request by detzgk**
* Fixed up .gitignore files to properly ignore /target/ (java) and venv (python) directories
* Found a reasonable version of spring-boot to pin to based on https://github.com/diagridio/issues/issues/3821 -- dapr-sdk-springboot uses the 2.7 series so I took the latest version of that since the older versions have a documented vulnerability
* Removed package-lock.json files from python projects

### CODE REVIEW

**Comment by Eileen-Yu** [comment]
@detzgk  thank you sooooo much for helping with this and save a java noob!!

just want to check have you tested it manually on local? for me java works fine but there seems some error for python, as it would hang a while then throw 
```
== APP - orderapp == Health check on https://http-prj235919.api.dev.cloud.diagrid.io/v1.0/healthz/outbound failed: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)
```

sry I'm not a python expert so just want to check if you meet with same issue, or maybe something wrong in my env

**Review by Eileen-Yu — COMMENTED** [review]
@detzgk thank you sooooo much for helping with this and save a java noob!!

just want to check have you tested it manually on local? for me java works fine but there seems some error for python, as it would hang a while then throw

```
== APP - orderapp == Health check on https://http-prj235919.api.dev.cloud.diagrid.io/v1.0/healthz/outbound failed: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)
```
sry I'm not a python expert either so just want to check if you meet with same issue, or maybe something wrong in my env

**Comment by detzgk** [comment]
> @detzgk thank you sooooo much for helping with this and save a java noob!!
> 
> just want to check have you tested it manually on local? for me java works fine but there seems some error for python, as it would hang a while then throw
> 
> ```
> == APP - orderapp == Health check on https://http-prj235919.api.dev.cloud.diagrid.io/v1.0/healthz/outbound failed: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)
> ```
> 
> sry I'm not a python expert either so just want to check if you meet with same issue, or maybe something wrong in my env

I haven't tested that no. None of the changes I've made to the Python code should affect the way it runs, I'm just tidying up the repo a little. I'll see if I can take a look at it shortly.

**Comment by detzgk** [comment]
@Eileen-Yu I'm unable to reproduce that error locally, either using the CLI quickstart feature and following the instructions, or by manually setting env vars and running it directly from a checkout of the quickstart repo.

**Review by Eileen-Yu — APPROVED** [review]
if things all run smoothly then let's merge it, thankuuuu!

**Pull request merged**
